version: '3.8'

services:
  frontend:
    build: 
      context: ./plagiguard-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
      - NODE_ENV=production

  backend:
    build:
      context: ./PlagiGuard-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/plagiguard
      - SPRING_REDIS_HOST=redis
      - AI_SERVICE_URL=http://ai-service:5000
      - SPRING_PROFILES_ACTIVE=prod

  ai-service:
    build:
      context: ./PlagiGuard-Backend/py
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MODEL_PATH=/app/models
      - PYTORCH_DEVICE=cpu
    volumes:
      - ./models:/app/models

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plagiguard
      - POSTGRES_USER=plagiguard
      - POSTGRES_PASSWORD=securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
